import "./_styles/globals.css";

export const metadata = {
  title: {
    template: "%s | medical hospital",
    default: "welcome | medical hospital",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col h-dvh">
          <main className="flex-1 ">{children}</main>
        </div>
      </body>
    </html>
  );
}
