import { Poppins } from "next/font/google";

// const poppins = Poppins({
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
//   subsets: ["latin"],
//   display: "swap",
// });

import "./_styles/globals.css";
import { Toaster } from "react-hot-toast";
import { PredictProvider } from "./_context/predictContext";

export const metadata = {
  title: {
    template: "%s | medical hospital",
    default: "welcome | medical hospital",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const poppinsClass = poppins.className;
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Toaster position="bottom-right" />
        <div className="flex flex-col h-dvh">
          <PredictProvider>
            <main className="flex-1 h-full  ">{children}</main>
          </PredictProvider>
        </div>
      </body>
    </html>
  );
}
